/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#43474f",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#00522c",
        "secondary-fixed-dim": "#50e08d",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#004f4f",
        "primary-fixed-dim": "#a9c7ff",
        "inverse-on-surface": "#ecf0ff",
        "surface-container-lowest": "#ffffff",
        "on-error-container": "#93000a",
        primary: "#001939",
        "tertiary-fixed-dim": "#76d6d5",
        error: "#ba1a1a",
        tertiary: "#001d1d",
        "secondary-container": "#70fda7",
        "surface-dim": "#d4daea",
        "on-primary-fixed": "#001b3d",
        "on-error": "#ffffff",
        "tertiary-container": "#003434",
        "outline-variant": "#c3c6d0",
        surface: "#f9f9ff",
        "primary-fixed": "#d6e3ff",
        "tertiary-fixed": "#93f2f2",
        "inverse-primary": "#a9c7ff",
        "on-primary-container": "#7696cd",
        "surface-container-highest": "#dde2f3",
        "on-surface": "#161c27",
        outline: "#747780",
        "surface-container": "#e8eeff",
        "surface-container-high": "#e3e8f9",
        "primary-container": "#002d5e",
        "on-background": "#161c27",
        "on-tertiary-fixed": "#002020",
        "on-secondary": "#ffffff",
        "surface-tint": "#3e5f92",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#f1f3ff",
        "on-secondary-container": "#007440",
        "inverse-surface": "#2a303d",
        secondary: "#006d3c",
        "secondary-fixed": "#70fda7",
        background: "#f9f9ff",
        "on-tertiary-container": "#40a4a3",
        "surface-variant": "#dde2f3",
        "on-secondary-fixed": "#00210e",
        "on-primary-fixed-variant": "#244779",
        "surface-bright": "#f9f9ff",
      },

      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },

      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
};
